-- =====================================================================
-- GetTennisSponsors — 12-month curated news backfill (real, sourced)
-- Supersedes 05_news_curated_seed.sql. Longer bodies framed as sponsor
-- EXPOSURE (so brands want to be featured). source='operator' (Curated).
-- Run in Supabase SQL Editor after 04_news.sql. Safe to re-run.
-- author_name = the sponsor/brand or governing body (the exposure subject).
-- =====================================================================

delete from news_posts where source = 'operator';

insert into news_posts (title, body, author_name, author_type, country, link_url, source, status, published_at) values
('Mercedes-Benz becomes the WTA''s Premier and Exclusive Automobile Partner',
 'Mercedes-Benz has signed a long-term deal to become the Premier Partner and Exclusive Automobile Partner of the WTA, effective 1 January 2026 — described as the most significant partnership in WTA history. The agreement places the Mercedes-Benz brand across the Hologic WTA Tour''s global calendar, from on-court branding to digital and hospitality activations, reaching the tour''s worldwide fanbase. It signals how premium automotive brands are using women''s tennis to build prestige and global reach.',
 'Mercedes-Benz','operator','DE','https://www.wtatennis.com/news/4417616/wta-and-mercedes-benz-announce-long-term-partnership','operator','published','2025-12-10'),
('ATP and EQT announce global partnership through 2030',
 'The ATP has named global investment organisation EQT its first official private markets partner and a Platinum Partner through 2030. EQT activates across ATP Masters 1000, 500 and 250 tournaments throughout the season, connecting the brand with a global tennis audience of more than one billion fans. For EQT it is a long-runway platform for sustained international brand exposure tied to elite men''s tennis.',
 'EQT','operator','SE','https://www.atptour.com/en/news/atp-eqt-partnership-announcement-june-2026','operator','published','2026-06-09'),
('Verizon lands landmark U.S. partnership with the ATP and WTA Tours',
 'Verizon became the first telecommunications partner of the ATP and the official telecoms partner of both tours for U.S. events, in a multi-year agreement that secures category exclusivity in 5G. The deal gives Verizon integrated visibility across the U.S. tournament calendar and Tennis Channel properties under one package. It is a template for how a single brand can own a category across the American tennis season.',
 'Verizon','operator','US','https://www.atptour.com/en/news/verizon-announcement-2025','operator','published','2025-05-12'),
('Tennis Channel and Sinclair open a single U.S. sponsorship gateway for the ATP and WTA',
 'Sinclair and its Tennis Channel announced a first-of-its-kind partnership letting sponsors access both the ATP and Hologic WTA U.S. calendars plus all Tennis Channel platforms under one comprehensive package. The structure lowers the barrier for brands to reach U.S. tennis audiences across broadcast, streaming and on-site at once. Verizon was unveiled as the first integrated sponsor under the model.',
 'Tennis Channel (Sinclair)','operator','US','https://www.sportsvideo.org/2025/05/09/sinclair-atp-wta-and-u-s-based-tennis-tournaments-announce-sponsorship-partnership-verizon-signs-multi-year-agreement-as-first-integrated-sponsor/','operator','published','2025-05-09'),
('PIF and EQT named official partners of the 2026 HSBC Championships',
 'Saudi Arabia''s Public Investment Fund (PIF) and EQT have become official partners of the LTA''s Queen''s Club Championships, staged as the HSBC Championships. The multi-year deals add global investment brands to one of the grass season''s marquee events, with on-site and broadcast exposure in the run-up to Wimbledon. It underlines how heritage British tennis is attracting major international sponsors.',
 'Public Investment Fund (PIF)','operator','GB','https://www.lta.org.uk/news/2026/june/new-atp-global-partners-announced-for-2026-hsbc-championships/','operator','published','2026-06-05'),
('HSBC becomes title sponsor of the Queen''s Club Championships',
 'The LTA named HSBC the new title sponsor of the Queen''s Club Championships, which now runs as the HSBC Championships. The naming-rights deal puts HSBC front and centre across one of the most prestigious grass-court events on the calendar, from court branding to broadcast mentions. Title sponsorship of a heritage event remains one of the highest-visibility assets in tennis.',
 'HSBC','operator','GB','https://en.wikipedia.org/wiki/Queen%27s_Club_Championships','operator','published','2025-07-02'),
('Nitto Denko extends ATP Finals title partnership through 2030',
 'Japanese materials company Nitto extended its title partnership of the season-ending ATP Finals for another five years, to 2030. As title sponsor of the Nitto ATP Finals in Turin, the brand earns sustained global exposure at the sport''s premier year-end event featuring the world''s top eight. Long renewals like this show how title partners compound brand equity by staying with a marquee property.',
 'Nitto Denko','operator','IT','https://en.wikipedia.org/wiki/ATP_Finals','operator','published','2025-11-20'),
('Bank of China (Hong Kong) renews title sponsorship of the Hong Kong Tennis Open',
 'Bank of China (Hong Kong) returns as title sponsor of the ATP 250 Bank of China Hong Kong Tennis Open. The naming-rights renewal keeps the bank''s brand on a growing Asian stop on the men''s tour, with city-wide visibility and hospitality around the event. It is an example of a regional financial brand anchoring itself to a home-market tournament.',
 'Bank of China (Hong Kong)','operator','HK','https://www.tennishk.org/en/press-release/bank-of-china-hong-kong-continues-title-sponsorship-at-the-atp-250-mens-professional-tennis-tournament/','operator','published','2025-12-15'),
('Danone signs Carlos Alcaraz as a global ambassador',
 'Danone signed world No. 1 Carlos Alcaraz as a global ambassador in 2025, making him a face of its Evian water and high-protein dairy lines. The deal plugs Danone into one of the most marketable athletes in sport, with global campaign and content rights. Alcaraz''s endorsement roster — reported to include Nike, Rolex, Louis Vuitton and BMW — shows the premium brands competing for tennis''s next generation.',
 'Danone (Evian)','operator','ES','https://www.tennismajors.com/others-news/top-sponsored-tennis-players-and-their-biggest-brand-deals-814901.html','operator','published','2025-07-20'),
('Carlos Alcaraz tops 2025 endorsement earnings with a deep brand roster',
 'According to Last Word on Sports, Carlos Alcaraz led tennis off-court income in 2025 with roughly $35m in endorsements on top of prize money, anchored by Nike and partners including Rolex, Louis Vuitton and BMW. The numbers illustrate how a single tennis star can deliver category-spanning exposure for apparel, luxury, automotive and watch brands simultaneously.',
 'Nike','operator','ES','https://lastwordonsports.com/tennis/2025/08/25/highest-paid-tennis-players-2025-alcaraz-sinner-gauff/','operator','published','2025-08-25'),
('Gucci and Lavazza headline Jannik Sinner''s commercial portfolio',
 'World-class form turned Jannik Sinner into a marketing force in 2025, with off-court partners including Gucci and Lavazza reportedly adding around $27m in income. For these brands, Sinner offers premium Italian-rooted storytelling with global reach across the tour. His rise shows how fashion and lifestyle brands increasingly use tennis stars as year-round brand ambassadors.',
 'Gucci','operator','IT','https://lastwordonsports.com/tennis/2025/08/25/highest-paid-tennis-players-2025-alcaraz-sinner-gauff/','operator','published','2025-08-26'),
('New Balance powers Coco Gauff, the world''s highest-paid female athlete',
 'Coco Gauff was the highest-paid female athlete in 2025, with around $25m in endorsements alongside her prize money, working with brands including New Balance, Bose and Carol''s Daughter. For New Balance, Gauff is a flagship global face across apparel and footwear. She also launched Coco Gauff Enterprises, signalling athletes moving from endorsed talent to brand owners.',
 'New Balance','operator','US','https://lastwordonsports.com/tennis/2025/08/25/highest-paid-tennis-players-2025-alcaraz-sinner-gauff/','operator','published','2025-08-27'),
('Oshee becomes a headline sponsor for Iga Swiatek',
 'Iga Swiatek upgraded her commercial line-up with sports-drink brand Oshee, adding to a portfolio that includes racquet partner Tecnifibre. The deal gives the Polish brand association with one of the most consistent stars in women''s tennis and visibility across her global schedule. It is a strong example of a home-market brand scaling internationally through a top athlete.',
 'Oshee','operator','PL','https://www.tennismajors.com/others-news/top-sponsored-tennis-players-and-their-biggest-brand-deals-814901.html','operator','published','2025-09-05'),
('ASICS signs Lorenzo Musetti to a multi-year apparel deal',
 'Italian world-tour player Lorenzo Musetti, previously with Nike, signed a multi-year apparel and footwear deal with ASICS. The partnership gives ASICS prominent on-court visibility through a rising European star across the global calendar. Player apparel switches like this are watched closely as brands compete for the next wave of marketable talent.',
 'ASICS','operator','IT','https://www.tennis.com/baseline/articles/new-sponsors-apparel-2025-frances-tiafoe-lululemon-dimitrov-adidas-carlos-alcaraz-coach-nike-kalinskaya','operator','published','2025-07-10'),
('Hubert Hurkacz switches to adidas apparel and a new Wilson racquet',
 'Hubert Hurkacz moved from Yonex to adidas for apparel and footwear and adopted a new Wilson racquet for 2025. The changes give adidas and Wilson on-court exposure through a top-ranked player at events worldwide. Equipment and apparel partnerships remain among the most visible — and most contested — assets in professional tennis.',
 'adidas','operator','PL','https://www.tennisnerd.net/gear/pro-player-sponsorship-changes-in-2025/43834','operator','published','2025-07-15'),
('Madison Keys switches to a Yonex Ezone',
 'Madison Keys moved to a Yonex Ezone racquet for 2025, a season in which she captured a Grand Slam title. The equipment partnership delivers Yonex high-profile validation and visibility every time she competes. Racquet sponsorships convert on-court success directly into brand credibility for equipment makers.',
 'Yonex','operator','US','https://www.tennisnerd.net/gear/pro-player-sponsorship-changes-in-2025/43834','operator','published','2025-07-18'),
('Lululemon expands into tennis with Frances Tiafoe',
 'Athleisure brand Lululemon broadened its tennis presence by outfitting Frances Tiafoe, one of the U.S. game''s most charismatic stars. The deal puts Lululemon on court at marquee events and aligns the brand with American tennis''s growing entertainment appeal. It reflects lifestyle brands moving into performance tennis to reach new audiences.',
 'Lululemon','operator','US','https://www.tennis.com/baseline/articles/new-sponsors-apparel-2025-frances-tiafoe-lululemon-dimitrov-adidas-carlos-alcaraz-coach-nike-kalinskaya','operator','published','2025-07-22'),
('adidas overtakes Nike for on-court presence at the 2025 US Open',
 'At the 2025 US Open, adidas dressed 15 seeded players to Nike''s 11 — a notable shift from prior years when Nike dominated. The trend highlights how apparel visibility at a Grand Slam is a closely tracked proxy for brand momentum in tennis. For sponsors, seeded-player count at the majors is a tangible exposure metric.',
 'adidas','operator','US','https://www.sportico.com/leagues/tennis/2025/us-open-clothing-apparel-adidas-y3-nike-1234869274/','operator','published','2025-09-10'),
('Miami Open expands its global partnership portfolio for 2026',
 'The Miami Open presented by Itaú confirmed returning platinum sponsors — including Public Investment Fund, Cadillac, Emirates and Lacoste — and added new partners for 2026. The roster shows how a Masters-level event packages premium hospitality, on-site and digital exposure for a deep bench of global brands. Itaú''s presenting partnership anchors the tournament''s commercial identity.',
 'Miami Open','operator','US','https://www.miamiopen.com/latest-news/miami-open-expands-global-partnership-portfolio/','operator','published','2026-03-01'),
('Betsson named Official Sports Betting Partner of the Davis Cup',
 'Betsson partnered with the Davis Cup — the World Cup of Tennis — as its official sports betting partner for 2026. The deal gives the brand exposure across a global team competition staged in multiple host nations. Governing-body partnerships like this let brands reach national tennis audiences worldwide through a single property.',
 'Betsson','operator','SE','https://www.itftennis.com/en/about-us/organisation/commercial-partners/','operator','published','2026-01-20'),
('US Open confirms its 2026 partner roster',
 'The US Open published its slate of official partners for the 2026 championships, with Emirates and Rolex among brands that sponsor across the Grand Slams. The Flushing Meadows roster is one of the largest in tennis, offering brands fortnight-long global exposure. The breadth of categories shows the commercial pull of a major in a top media market.',
 'US Open','operator','US','https://www.usopen.org/en_US/about/partners.html','operator','published','2026-06-18');
